Content:
    - framework/doc/content
    - modules/solid_properties/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: MOOSE Solid Properties Module
    repo: https://github.com/idaholab/moose
    home: /modules/solid_properties

Extensions:
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/solid_properties
        allow-test-objects: False
        hide:
            framework: !include framework/doc/hidden.yml
            solid_properties: !include modules/solid_properties/doc/hidden.yml
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/solid_properties/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
